### PR TITLE
Add support for unbinding third-party IDs when they are removed from the user account

### PR DESCRIPTION
**Pull request by anoadragon453**
This is intended to be used with the `on_add_user_third_party_identifier` and `on_remove_user_third_party_identifier` module API callbacks added in https://github.com/matrix-org/synapse/pull/15044. That PR also deprecates `on_threepid_bind`, hence replacing it here.

Recommended to review commit-by-commit. Supercedes #2.

**Note:** CI is currently completely failing due to this PR requiring Synapse v1.79 (which is yet to be released). But it passes locally :)

**Current status:** I would like a review on this PR, but we can't merge it until Synapse v1.79 is released with the Module APIs that it requires.

### CODE REVIEW

**Review by reivilibre — APPROVED** [review]
obviously it's a bit lacking in reliability in that there's no retry mechanism etc, but that is probably fine most of the time and fine for a start.

**Comment by anoadragon453** [comment]
> obviously it's a bit lacking in reliability in that there's no retry mechanism etc, but that is probably fine most of the time and fine for a start.

Yeahhhh, I was cribbing off the other method's choice of:

```
# If there was an error, the IS is likely unreachable, so don't try again.
```

but we ought to revisit that in an issue - I can imagine there's probably cases where the IS is just overloaded and times out, and we should probably back off and retry a few times.

Additionally, since this method will block Synapse returning requests to the client while it runs, it would be nice to kick off the request to the IS asynchronously and not block Synapse.

...looks like I have some issues to write up.

**Comment by reivilibre** [comment]
That's fine, I was thinking more *persistent* retries to be honest, e.g. if the IS really is down, but (depending on use case) it'd probably be nice if it still sorted itself out eventually. But adding storage to the module sounds like a big chunk of work

**Comment by anoadragon453** [comment]
Providing storage is actually pretty simple, as Synapse provides DB a [`run_db_interaction`](https://github.com/matrix-org/synapse/blob/b40657314e03583f45ad49504711698a70735313/synapse/module_api/__init__.py#L872) method to modules!

I've created a couple relevant issues:

* https://github.com/matrix-org/synapse-bind-sydent/issues/5 (This module blocks Synapse while waiting for Sydent to respond to the bind/unbind request)
* https://github.com/matrix-org/synapse-bind-sydent/issues/6 (There are no retries if a request to Sydent fails)

**Comment by anoadragon453** [comment]
I temporarily modified the CI config in https://github.com/matrix-org/synapse-bind-sydent/pull/3/commits/94b260d98be8f96a45617b306321ed639086af93 in order to test against the upcoming Synapse v1.79 release. CI passed on that commit, hence this PR should continue to pass CI (and can be merged) once Synapse v1.79 is released (due Tuesday, March 14 2023).

**Comment by anoadragon453** [comment]
Synapse v1.79.0 has [been released](https://github.com/matrix-org/synapse/releases/tag/v1.79.0), and CI on this PR now passes. We're good to merge.

**Pull request merged**
